services:
  app:
    image: bellsoft/liberica-openjdk-alpine:11.0.16.1-1
    command: javadoc -sourcepath /app/src/main/java -cp /app/out -d /app/doc -subpackages homework1
    volumes:
     - ./bin:/app/out
     - ./src:/app/src
     - ./doc:/app/doc